### PR TITLE
flake8 fixes + travis integration

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by Alir3z4** [comment]
@nikolas This is great.
Thanks

Could you please also update the changelog as well?

**Comment by nikolas** [comment]
i've updated the changelog here

**Comment by Alir3z4** [comment]
@nikolas There's conflicts due to #25 changes on the changelog file.

**Comment by nikolas** [comment]
I've rebase my branch to resolve the conflict

**Comment by Alir3z4** [comment]
@nikolas Thanks, the patch has been merged.
I'll issue a release soon.

**Pull request merged**
