### PR TITLE
Add compatibility with commonmark-0.6.0

### PR DESCRIPTION
**Pull request by nikolas**
CommonMark-py 0.6.0 has a new API.

### CODE REVIEW

**Comment by Alir3z4** [comment]
Thanks for the great work.
Travis show failure due to Python 3.3

Should we drop it ?

**Comment by nikolas** [comment]
I'd like to understand why it's failing.. I'll look into it.

**Comment by nikolas** [comment]
Oh well, I saw you dropped it. That's fine -- I only use 2.7, 3.4, and 3.5 anyways. I've rebased all my pull requests so they should pass now.

**Comment by nikolas** [comment]
I think py3.3 was failing because django 1.9 dropped support for python 3.3, and our latest travis builds were downloading django 1.9 automatically. See commit 8fcb6679fd2404f4c5c607e9b22e958eb463e65a

**Comment by Alir3z4** [comment]
Awesome, that's great.
Could you please update the ChangeLog with your latest changes ? then I'll bump the version and issue a new release.

**Comment by nikolas** [comment]
done

**Pull request merged**
